version: 0.2

phases:
  build:
    commands:
      
      - git clone https://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@github.com/captain-omkar/manifest.git manifest
      - cd manifest
      - ls
      
      # Add a file to the repository
      - echo "Hello, world!" > new_file.txt
      - ls
      - git config --global user.email "omkarchavanbldea@gmail.com"
      - git config --global user.name "captain-omkar"
      - git add .
      
      # Commit and push the changes
      - git commit -m "Added new_file.txt"
      - git remote -v
      - git push 
